name: GoLang and Python Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      - name: Verify build
        run: go build -o TMT-2 .

      - name: Run tests
        run: go test . -v

      - name: Upload Go game binary
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: TMT-2

  build-python:
    runs-on: ubuntu-latest
    needs: build-go

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download Go game binary
        uses: actions/download-artifact@v4
        with:
          name: go-binary
          path: .

      - name: Make Go binary executable
        run: chmod +x TMT-2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame

      - name: Verify Python build
        run: |
          python -m py_compile game.py

      - name: Run Python script
        run: python game.py
